"""empty message

Revision ID: 94c195ebcb23
Revises: 077069c45709
Create Date: 2022-05-13 13:26:07.720607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c195ebcb23'
down_revision = '077069c45709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('numFivesInRow', sa.Integer(), nullable=False))
    op.alter_column('cards', 'curr_rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'curr_rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('cards', 'numFivesInRow')
    # ### end Alembic commands ###
